import type { WorldManifest } from "@/types/world";

export const WORLD_MANIFESTS: WorldManifest[] = [
  {
    id: "apple-world",
    name: "Apple World",
    description: "Minimalist design with precision animations and glass morphism",
    route: "/worlds/apple",
    thumbnail: "/icons/worlds/apple.svg",
    theme: {} as WorldManifest["theme"],
    animation: {
      engine: "framer",
      pageTransition: { type: "fade", duration: 0.5 },
      scrollAnimations: { enabled: true, parallax: false, reveal: true, scrub: false },
      hoverEffects: { type: "scale", intensity: 1.05, duration: 0.3 },
      loadingAnimation: { type: "skeleton", duration: 0.8 },
    },
    cursor: { type: "custom", size: 8, color: "#000000", blendMode: "difference" },
    typography: {
      headingFont: "SF Pro Display",
      bodyFont: "SF Pro Text",
      monoFont: "SF Mono",
      scale: 1,
    },
    metadata: {
      author: "Frontend Multiverse",
      version: "1.0.0",
      createdAt: "2026-01-01",
      tags: ["minimal", "clean", "apple"],
    },
  },
  {
    id: "cyberpunk-world",
    name: "Cyberpunk World",
    description: "Neon-lit dystopia with glitch effects and holographic elements",
    route: "/worlds/cyberpunk",
    thumbnail: "/icons/worlds/cyberpunk.svg",
    theme: {} as WorldManifest["theme"],
    animation: {
      engine: "gsap",
      pageTransition: { type: "custom", duration: 0.8 },
      scrollAnimations: { enabled: true, parallax: true, reveal: true, scrub: true },
      hoverEffects: { type: "glow", intensity: 2, duration: 0.2 },
      loadingAnimation: { type: "custom", duration: 1.5 },
    },
    cursor: { type: "custom", size: 12, color: "#00ffff", blendMode: "screen" },
    typography: {
      headingFont: "Orbitron",
      bodyFont: "Rajdhani",
      monoFont: "Share Tech Mono",
      scale: 1.1,
    },
    metadata: {
      author: "Frontend Multiverse",
      version: "1.0.0",
      createdAt: "2026-01-01",
      tags: ["cyberpunk", "neon", "glitch"],
    },
  },
  {
    id: "space-world",
    name: "Space World",
    description: "Cosmic exploration with 3D scenes and stellar animations",
    route: "/worlds/space",
    thumbnail: "/icons/worlds/space.svg",
    theme: {} as WorldManifest["theme"],
    animation: {
      engine: "three",
      pageTransition: { type: "scale", duration: 1 },
      scrollAnimations: { enabled: true, parallax: true, reveal: true, scrub: true },
      hoverEffects: { type: "magnetic", intensity: 1.5, duration: 0.4 },
      loadingAnimation: { type: "custom", duration: 2 },
    },
    cursor: { type: "custom", size: 16, color: "#ffffff", blendMode: "screen" },
    typography: {
      headingFont: "Space Grotesk",
      bodyFont: "Inter",
      monoFont: "JetBrains Mono",
      scale: 1,
    },
    metadata: {
      author: "Frontend Multiverse",
      version: "1.0.0",
      createdAt: "2026-01-01",
      tags: ["space", "3d", "cosmic"],
    },
  },
  {
    id: "gaming-world",
    name: "Gaming World",
    description: "High-energy gaming aesthetic with pixel art and arcade vibes",
    route: "/worlds/gaming",
    thumbnail: "/icons/worlds/gaming.svg",
    theme: {} as WorldManifest["theme"],
    animation: {
      engine: "gsap",
      pageTransition: { type: "slide", duration: 0.4 },
      scrollAnimations: { enabled: true, parallax: false, reveal: true, scrub: false },
      hoverEffects: { type: "scale", intensity: 1.1, duration: 0.15 },
      loadingAnimation: { type: "spinner", duration: 1 },
    },
    cursor: { type: "custom", size: 10, color: "#ff0000", blendMode: "normal" },
    typography: {
      headingFont: "Press Start 2P",
      bodyFont: "Exo 2",
      monoFont: "VT323",
      scale: 1.2,
    },
    metadata: {
      author: "Frontend Multiverse",
      version: "1.0.0",
      createdAt: "2026-01-01",
      tags: ["gaming", "pixel", "arcade"],
    },
  },
  {
    id: "ai-world",
    name: "AI World",
    description: "Futuristic AI aesthetic with neural networks and fluid visuals",
    route: "/worlds/ai",
    thumbnail: "/icons/worlds/ai.svg",
    theme: {} as WorldManifest["theme"],
    animation: {
      engine: "framer",
      pageTransition: { type: "fade", duration: 0.6 },
      scrollAnimations: { enabled: true, parallax: true, reveal: true, scrub: false },
      hoverEffects: { type: "glow", intensity: 1.5, duration: 0.3 },
      loadingAnimation: { type: "custom", duration: 1.8 },
    },
    cursor: { type: "custom", size: 14, color: "#7c3aed", blendMode: "screen" },
    typography: {
      headingFont: "Space Grotesk",
      bodyFont: "Inter",
      monoFont: "Fira Code",
      scale: 1,
    },
    metadata: {
      author: "Frontend Multiverse",
      version: "1.0.0",
      createdAt: "2026-01-01",
      tags: ["ai", "neural", "futuristic"],
    },
  },
  {
    id: "editorial-world",
    name: "Editorial World",
    description: "Magazine-inspired typography and editorial layout design",
    route: "/worlds/editorial",
    thumbnail: "/icons/worlds/editorial.svg",
    theme: {} as WorldManifest["theme"],
    animation: {
      engine: "framer",
      pageTransition: { type: "slide", duration: 0.5 },
      scrollAnimations: { enabled: true, parallax: false, reveal: true, scrub: false },
      hoverEffects: { type: "scale", intensity: 1.02, duration: 0.4 },
      loadingAnimation: { type: "skeleton", duration: 0.6 },
    },
    cursor: { type: "default", size: 24, color: "#000000", blendMode: "normal" },
    typography: {
      headingFont: "Playfair Display",
      bodyFont: "Source Serif 4",
      monoFont: "IBM Plex Mono",
      scale: 1,
    },
    metadata: {
      author: "Frontend Multiverse",
      version: "1.0.0",
      createdAt: "2026-01-01",
      tags: ["editorial", "typography", "magazine"],
    },
  },
  {
    id: "liquid-world",
    name: "Liquid World",
    description: "Fluid morphing shapes with WebGL shaders and organic motion",
    route: "/worlds/liquid",
    thumbnail: "/icons/worlds/liquid.svg",
    theme: {} as WorldManifest["theme"],
    animation: {
      engine: "three",
      pageTransition: { type: "custom", duration: 1.2 },
      scrollAnimations: { enabled: true, parallax: true, reveal: true, scrub: true },
      hoverEffects: { type: "magnetic", intensity: 2, duration: 0.5 },
      loadingAnimation: { type: "custom", duration: 2.5 },
    },
    cursor: { type: "custom", size: 20, color: "#06b6d4", blendMode: "screen" },
    typography: {
      headingFont: "Outfit",
      bodyFont: "Plus Jakarta Sans",
      monoFont: "JetBrains Mono",
      scale: 1,
    },
    metadata: {
      author: "Frontend Multiverse",
      version: "1.0.0",
      createdAt: "2026-01-01",
      tags: ["liquid", "fluid", "webgl"],
    },
  },
  {
    id: "brutalist-world",
    name: "Brutalist World",
    description: "Raw, unpolished design with bold typography and stark contrasts",
    route: "/worlds/brutalist",
    thumbnail: "/icons/worlds/brutalist.svg",
    theme: {} as WorldManifest["theme"],
    animation: {
      engine: "gsap",
      pageTransition: { type: "custom", duration: 0.3 },
      scrollAnimations: { enabled: true, parallax: false, reveal: true, scrub: false },
      hoverEffects: { type: "rotate", intensity: 5, duration: 0.1 },
      loadingAnimation: { type: "spinner", duration: 0.5 },
    },
    cursor: { type: "none", size: 0, color: "#000000", blendMode: "normal" },
    typography: {
      headingFont: "Anton",
      bodyFont: "Space Mono",
      monoFont: "Courier Prime",
      scale: 1.3,
    },
    metadata: {
      author: "Frontend Multiverse",
      version: "1.0.0",
      createdAt: "2026-01-01",
      tags: ["brutalist", "raw", "bold"],
    },
  },
  {
    id: "retro-world",
    name: "Retro World",
    description: "Nostalgic retro computing with CRT effects and terminal aesthetics",
    route: "/worlds/retro",
    thumbnail: "/icons/worlds/retro.svg",
    theme: {} as WorldManifest["theme"],
    animation: {
      engine: "css",
      pageTransition: { type: "fade", duration: 0.8 },
      scrollAnimations: { enabled: true, parallax: false, reveal: true, scrub: false },
      hoverEffects: { type: "glow", intensity: 1, duration: 0.3 },
      loadingAnimation: { type: "custom", duration: 1.5 },
    },
    cursor: { type: "custom", size: 8, color: "#00ff00", blendMode: "screen" },
    typography: {
      headingFont: "VT323",
      bodyFont: "IBM Plex Mono",
      monoFont: "VT323",
      scale: 1,
    },
    metadata: {
      author: "Frontend Multiverse",
      version: "1.0.0",
      createdAt: "2026-01-01",
      tags: ["retro", "terminal", "crt"],
    },
  },
  {
    id: "experimental-world",
    name: "Experimental World",
    description: "Pushing boundaries with unconventional layouts and interactions",
    route: "/worlds/experimental",
    thumbnail: "/icons/worlds/experimental.svg",
    theme: {} as WorldManifest["theme"],
    animation: {
      engine: "gsap",
      pageTransition: { type: "custom", duration: 1.5 },
      scrollAnimations: { enabled: true, parallax: true, reveal: true, scrub: true },
      hoverEffects: { type: "magnetic", intensity: 3, duration: 0.6 },
      loadingAnimation: { type: "custom", duration: 3 },
    },
    cursor: { type: "custom", size: 32, color: "#f59e0b", blendMode: "difference" },
    typography: {
      headingFont: "Syne",
      bodyFont: "General Sans",
      monoFont: "Fira Code",
      scale: 1,
    },
    metadata: {
      author: "Frontend Multiverse",
      version: "1.0.0",
      createdAt: "2026-01-01",
      tags: ["experimental", "avant-garde", "experimental"],
    },
  },
];
